[package]
name = "metricity"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.19.0"

[dev-dependencies]
cfg-if = "1.0.0" # NOTE: Required for IDE completion when working with thread_local! macro
